[package]
name = "gnbpcap-tauri"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
gnbpcap-core = { path = "../gnbpcap-core" }
tauri = { version = "1.6", features = ["dialog-open"] }

[features]
custom-protocol = ["tauri/custom-protocol"]
